### ISSUE TITLE
I wanted to start the project, but nothing was shown

### ISSUE THREAD

**Issue by jvanlangen** [Sibyx/BinksRouter#4]
No uI or error is shown when starting the application. I found this in the event viewer:

Windows 10 pro

Application: BinksRouter.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at SharpPcap.Npcap.SafeNativeMethods.pcap_findalldevs(IntPtr ByRef, System.Text.StringBuilder)
   at SharpPcap.Npcap.NpcapDeviceList.Devices()
   at SharpPcap.Npcap.NpcapDeviceList.Refresh()
   at SharpPcap.Npcap.NpcapDeviceList..ctor()
   at SharpPcap.Npcap.NpcapDeviceList.get_Instance()
   at BinksRouter.Network.NetworkRouter..ctor()
   at BinksRouter.App..ctor()
   at BinksRouter.App.Main()

**Comment by Sibyx** [comment]
Hello @jvanlangen,

It's been a while since I last opened this project. From what I can see and remember, it seems like you haven't installed [npcap](https://npcap.com/#download) on your system. Please try installing it and let me know if that resolves the issue.

Additionally, I'm curious about what you're trying to achieve. This repository was created for an academic assignment, with the source code being the "interesting" part—not the binaries.
